### ISSUE TITLE
[STORY] Clean up spefications of analysis classes

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/arcana#130]
### Metadata

Epic: #17 
Feature: Australian-Imaging-Service/pipelines#14
Feature Release: 1

### Description

Finalise specification of analysis classes via decorators.

### Tasks

- [x] New unit tests to cover exceptions
- [x] check inherited_from statements to ensure that it is referencing first class in MRO that contains attribute
- [x] ensure that inherited pipelines don't remove outputs unless they explicitly set them to (output_name, NOTHING)
- [x] add `_dataset` attribute to analysis classes
- [x] check analysis classes for reserved names (dataset, menu, stack, anything else...)
- [x] supported nested 'mapped_from' by "linked list" of nested tuples
- [x] support passing sub analysis parameters by expanding SubanalysisDefault (renamed to SubanalysisInit) to take an argument with a dict
